name: final_countdown
description: A new Flutter project.

version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  fx: ^0.0.1
  flip_panel: ^0.0.8
  image_picker: ^0.4.10
  shared_preferences: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets: 
    - assets/brushed_metal.jpg
    - assets/wood.jpg
    - assets/wood_planks.jpg