name: final_countdown
description: A new Flutter project.

version: 0.0.1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  camera: ^0.2.4
  cupertino_icons: ^0.1.2
  fx: ^0.0.1
  flip_panel: ^0.0.8
  image_picker: ^0.4.10
  path_provider: ^0.4.1
  shared_preferences: ^0.4.3
  rxdart: ^0.19.0
  watcher: ^0.9.7
  async: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Fascinate_Inline
      fonts: 
        - asset: assets/Fascinate_Inline/FascinateInline-Regular.ttf

  assets: 
    - assets/camera_top.png
    - assets/camera_bottom.png
    - assets/filmstrip_edge.jpg
    - assets/wood.jpg
